GET http://localhost:8080/mackenzie/areas
Accept: application/json

###

GET http://localhost:8080/mackenzie/areas/1
Accept: application/json

###

POST http://localhost:8080/mackenzie/areas
Content-Type: application/json

{
  "nome": "Segurança da Informação"
}

###

PUT http://localhost:8080/mackenzie/areas/1
Content-Type: application/json

{
  "nome": "Desenvolvimento Web e Mobile"
}

###

DELETE http://localhost:8080/mackenzie/areas/5