GET - Lista todas as empresas
GET http://localhost:8080/mackenzie/empresas
Accept: application/json

###

GET - Busca empresa por ID
GET http://localhost:8080/mackenzie/empresas/1
Accept: application/json

###

POST - Cria nova empresa
POST http://localhost:8080/mackenzie/empresas
Content-Type: application/json

{
  "nome": "Nova Empresa Exemplo",
  "cnpj": "44.555.666/0001-77",
  "email": "contato@novaempresa.com"
}

###

PUT - Atualiza empresa existente
PUT http://localhost:8080/mackenzie/empresas/2
Content-Type: application/json

{
  "nome": "Beta Comércio Atualizado",
  "cnpj": "98.765.432/0001-10",
  "email": "beta@comercioatualizado.com"
}

###

DELETE - Remove empresa por ID
DELETE http://localhost:8080/mackenzie/empresas/3