GET http://localhost:8080/mackenzie/inscricoes
Accept: application/json

###

GET http://localhost:8080/mackenzie/inscricoes/1
Accept: application/json

###

POST http://localhost:8080/mackenzie/inscricoes
Content-Type: application/json

{
  "dataInscricao": "2025-10-25",
  "status": "Em análise",
  "mensagemApresentacao": "Tenho experiência com Java e estou interessado na vaga.",
  "estudante": {
    "id": 3
  },
  "vaga": {
    "id": 2
  }
}

###

PUT http://localhost:8080/mackenzie/inscricoes/1
Content-Type: application/json

{
  "dataInscricao": "2025-10-26",
  "status": "Aprovado",
  "mensagemApresentacao": "Feliz por participar do processo!",
  "estudante": {
    "id": 3
  },
  "vaga": {
    "id": 2
  }
}

###

DELETE http://localhost:8080/mackenzie/inscricoes/1